project:
  type: book
  output-dir: build/

lang: ru

repo-url: &repo-url https://github.com/vsheg/naturoinformatics
site-url: https://inf.sheg.cc

book:
  title: Естествоинформатика
  subtitle: Вычислительная химия и биология
  author: Всеволод Щеголев
  google-analytics: "G-JZGJWN0T0F"
  page-navigation: true
  sidebar:
    logo: assets/logo.svg
    contents:
      - index.qmd
    collapse-level: 1
    tools:
      - icon: house
        href: https://sheg.cc
      - icon: github
        href: *repo-url
  chapters:
    - index.qmd
    - 00-intro/notation.qmd
    - part: Квантовая механика
      chapters:
        - 01-quantum-mechanincs/0-quantum-mechanics.qmd
        - 01-quantum-mechanincs/1-wave-function.qmd
        - 01-quantum-mechanincs/2-state-vectors.qmd
        - 01-quantum-mechanincs/3-schrodinger-equation.qmd
        - 01-quantum-mechanincs/4-hydrogen-like-ion.qmd
        - 01-quantum-mechanincs/5-basis-sets.qmd
    - part: Молекулярная динамика
      chapters:
        - 03-molecular-mechanics/1-interactions.qmd
        - 03-molecular-mechanics/2-integration.qmd
        - 03-molecular-mechanics/3-micro--and-macroparameters.qmd
        - 03-molecular-mechanics/4-force-fields.qmd
        - 03-molecular-mechanics/5-trajectories.qmd
    - part: Ускоренный семплинг
      chapters:
        - 05-enhanced-sampling/1-metadynamics.qmd
    - part: Виртуальный скрининг
      chapters:
        - 06-virtual-screening/1-docking.qmd
    - part: Рассчёт свободной энергии
      chapters:
        - 07-free-energy-calculation/1-fep.qmd
        - 07-free-energy-calculation/2-alchemy.qmd
    - part: Хемоинформатика
      chapters:
        - 08-chemoinformatics/1-chemoinformatics.qmd

bibliography: assets/citation.yaml
reference-section-title: Источники
csl: assets/gost-numeric.csl
link-citations: true

format:
  html:
    toc: true
    toc-location: left
    toc-title: Разделы
    toc-depth: 4
    html-math-method: mathjax
    theme:
      light:
        - cosmo
        - assets/custom.scss
      dark:
        - cosmo
        - assets/custom.scss
        - assets/dark.scss
    code-fold: true
    include-in-header:
      - assets/_macros.qmd
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 400px

mainfont: Georgia
fontsize: 13pt
linestretch: 1.25
reference-location: margin

callout-appearance: minimal

number-sections: false

crossref:
  fig-prefix: Рис
  tbl-prefix: Табл
  eq-prefix: Ур.

filters:
  - lightbox

lightbox: auto
fig-format: svg

number-depth: 2
cap-location: margin

references:
  - id: astley1987
    type: webpage
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    title: Never Gonna Give You Up
    author: Rick Astley
    issued: 1987
