# Добро пожаловать {.unnumbered}

Здесь опубликованы материалы по некоторым разделах теоретической химии^[физической, вычислительной и хемоинформатики] и биоинформатики, в первую очередь полезные в разработке лекарственных молекул. Достаточно мало актуальной информации по этой теме доступно на русском языке, что и послужило идеей к созданию этого сайта.

Собранные здесь материалы:

- *дополняются* и перерабатываются^[нумерация разделов и формул условна и предназначена для навигации по тексту во время чтения], вы можете предлагать правки в [Git репозитории]({{< meta repo-url >}}) или в Телеграм-чате [@{{< meta telegram-chat >}}](https://t.me/{{< meta telegram-chat >}}) канала [@{{< meta telegram-channel >}}](https://t.me/{{< meta telegram-channel >}});
- *специализированы* и адресованы человеку, имеющему представление о классической и статистической термодинамике, и базовые знания естественных наук, т/е в нормальном случае --- прослушавшему университетский курс физической химии и окончившему школу;
- *неинституциональны*, т/е не проходили строгого^[но проходили нестрогое: тексты, которые легли в основу этих материалов, были написанные мной в годы учёбы на Химфаке МГУ для курсовой и дипломной работ, т/е они хотя бы бегло, но *были* прочитаны другими неглупыми людьми] научного рецензирования, однако, материалы неоригинальны в том смысле, что являются переработкой конвенционально более «серьёзных» источников и снабжены^[там, где это возможно, полезно или необходимо] ссылками @astley1987 на них;
- *неформальны* и не подвергались пристальному литературному редактированию:
    - стиль изложения лишён ряда условностей, например, сокращения (см. [Обозначения](notation.qmd)) используются потому, что они нравятся *автору* (мне); аналогично --- форматирование, интонационное тире, сноски итд расставлены там, где *мне* это кажется уместным;
    - при отсутствии приемлемого эквивалента к-л англоязычного термина я стараюсь избегать ложной дихотомии между *изящностью русского слога* и *фактичностью изложения*, поэтому слова *семплинг* или *structure-based* используются в тексте на полных своих правах.

Порядок изложения выбран не *от простого к сложному*, а *от физичного к умозрительному*: сначала объясняются общие принципы, затем специальные. Это позволяет не срезать углы и не прибегать к аналогиям там, где истинный физический смысл может быть проиллюстрирован непосредственно. Каждый раздел старается дать минимальный теоретический контекст, достаточный для создания оформленного впечатления о предмете и дальнейшего развития темы.

К этому сайту следует относиться как к набору хорошо структурированных[^formatting] заметок, которые позволят быстро познакомиться с предметом, освежить его в памяти или найти нужную формулу без необходимости искать книгу или статью. Сайт не заменит хороший учебник.<!-- , их список вы найдёте в TODO. -->

[^formatting]: Повествование **не** ограничено рамками устной речи:

    - оно нелинейно (что не хорошо и не плохо);
    - текст обильно снабжён кросс-ссылками;
    - акценты расставлены не вводными словами, а форматированием и членением на разделы;
    - сноски на полях содержат детали и если непонятны могут быть проигнорированны при первом прочтении

Сайт не является пособием по программированию, однако, некоторые иллюстрации снабжены кодом на языках Python, R или Mathematica. Снова --- в иллюстративных целях.

```{python}

#| fig-width: 30%

import matplotlib.patches as ptc
import matplotlib.pyplot as plt
import numpy as np

n_circles = 5

angle = np.linspace(0, 2 * np.pi, n_circles + 1)
X = np.cos(angle)
Y = np.sin(angle)

cmap_name = 'rainbow'
cmap = plt.colormaps[cmap_name].resampled(n_circles)
colors = cmap(np.arange(0, n_circles))
cmap

radius = 1.5
alpha = 0.5

circles = [
    ptc.Circle((x, y), radius, alpha=alpha, color=c) for x, y, c in zip(X, Y, colors)
]

fig, ax = plt.subplots()

for cir in circles:
    ax.add_artist(cir)

range_ = np.array([-1, 1, -1, 1])

plt.axis(1.05 * range_ + radius * np.sign(range_))
plt.axis('off')
ax.set_aspect(aspect=1)

fig.savefig('assets/logo.svg', bbox_inches='tight', pad_inches=0)

```

Полнотекстовый поиск --- естественный способ навигации в интернете и на этом ресурсе. Надеюсь, вы найдёте 👀 здесь что-то полезное.

## Использование материалов

Материалы этого сайта доступны бесплатно под лицензией [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ru).