## Векторы состояния 

Система классических частиц может быть описана заданием всех координат $\bf q = q_1, \cdots, q_n$ и импульсов $\bf p = p_1, \cdots, p_n$, уравнения движения определяют её эволюцию в фазовом пространстве (подробнее см. [TODO]).

Состояние квантовой системы описывается вектором в гильбертовом пространстве [TODO]. Для обозначения _векторов состояния_ используется _бра-кет_^[от англ. bracket --- скобка] нотация Дирака (1939), так вектор столбец, называемый, _кет-вектором_ обозначается правой погнутой скобкой:
$$\ket{\psi} = \begin{pmatrix}\psi_1 \\ \vdots \\ \psi_n\end{pmatrix},$$
операция эрмитового сопряжения^[последовательное транспонирование и комплексное сопряжение] переводит кет-вектор в _бра-вектор_, обозначаемый левой погнутой скобкой:
$$ \bra{\psi} = \ket{\psi}^\dag = \begin{pmatrix}\psi_1 \\ \vdots \\ \psi_n\end{pmatrix}^* = (\psi_1^* \; \cdots \; \psi_n^*).$$

Скалярное произведение бра- на кет-вектор называют _амплитудой вероятности_ и в покомпонетной записи обозначают
$$ \bra{\phi} \ket{\psi} = \bra{\phi} \cdot \ket{\psi} = \sum_i \phi_i^* \psi_i.$$

Как и любой другой, вектор состояния $\ket{\psi}$ можно разложить по базисным векторам $\ket{e_1}, \cdots, \ket{e_k}$:

$$\ket{\psi} = \psi_{e_1} \ket{e_1} + \cdots \psi_{e_k} \ket{e_k},$$
где $\psi_{e_1}, \cdots, \psi_{e_k}$ --- компоненты вектора в базисе $\ket{e_1}, \cdots, \ket{e_k}$. Компоненты вектора $\ket{\psi}$ также могут быть записаны через скалярное произведение с базисными векторами, например, для компоненты $\psi_{e_1}$:
$$\psi_{e_1} = \bra{e_1} \ket{\psi} = (1 \hspace{0.5em} \underbrace{\hspace{0.5em} \cdots \quad 0}_0) \begin{pmatrix} \psi_{e_1} \\ \vdots \\ \psi_{e_k} \end{pmatrix},$$
где $\bra{e_1} \ket{\psi}$ --- амплитуда вероятностей [TODO]. Таким образом, становится понятен смысл разложения [TODO], вектор состояния $\ket{\psi}$ можно представить линейной комбинацией базисных векторов состояния, причём **коэффициенты этого разложения являются вероятностями**.

## Амплитуды вероятностей
Сложение амплитуды вероятностей

## Волновая функция

### Вероятностный подход
Интерференционная картина, проявляющаяся в опыте Юнга (1803) при прохождении света через 2 щели или аналогичная при прохождении электрона может быть описана в терминах вероятности попадания частицы в конкрутную область экрана. 

Вероятность $\dd \bb P$ обнаружения частицы в области пространства $\dd V$ задаётся отношением:
$$ \dd \bb P = |\Psi (\bf r, t)|^2 \dd V = \Psi^* \Psi \dd V,$$
где $\Psi$ --- комплексозначная функция, называемая _волновой_, а квадрат её модуля по определению есть вероятность, $\Psi^*$ --- её комплексно-сопряжённая. Для одномерного случая:
$$\bb P (a \le x \le b) = \int_a^b \Psi^* \Psi \dd x.$$
В этом построении волновая функция уподобляется плоской волне @eq-plane-wave, описывающей наблюдаемую интерференционную картину,
$$\Psi(x, t) = A e^{i (k x - \omega t)},$$
однако более продуктивно рассматривать волновую функцию как вектор состояния.

### Векторы состояния
Интерференционная картина, получаемая в результате двухщелевого эксперимента, может быть представлена набором координат $x_1, \cdots, x_k$, в которых зарегистрировано попадание электрона. Каждая координата $x_i$ --- конкретная реализация общего вектора состостояния $\ket{\psi}$ квантовой системы, более того, каждой координате соответствует свой вектор состояния $\ket{x_i}$, тогда согластно принципу суперпозиции разложение $\ket{\psi}$ можно записать виде линейной комбинации базисных векторов состояния с коэффициентами амплитуды вероятности $c_i \in \CC$:
$$\ket{\psi} = \sum_i c_i \ket{e_i} = \sum_i \bra{e_i} \ket{\Psi},$$
коэффициенты $c_i$ этого разложения определяются вектором $\ket \Psi$, называемым _волновой функцией_:
$$c_i = \bra{x_i} \ket{\Psi(x_i)},$$
т.е. значение волновой функции $\Psi$ в точке $x_i$ --- амплитуда вероятности обнаружения там частицы:
$$\ket{\psi} = \sum_i \Psi(x_i) \ket{x_i}.$$

Поскольку число исходов бессчётно, от дискретных координат $x_i$ следует перейти к непрерывному интегрированию:
$$\ket{\psi} = \int \Psi(x) \ket{x} \dd x.$$

Домножив обе части равенства на бра-вектор $\bra{\phi}$, получим
$$\bra{\phi} \ket{\psi} =
\bra{\phi} \int \Psi(x) \ket{x} \dd x =
\int \bra{\phi} \ket{x} \Psi(x)\dd x =
\int \bra{x} \ket{\phi}^* \Psi(x) \dd x,$$
где $\bra{x} \ket{\phi}$ --- амплитуда вероятности, которой можно поставить другую волновую функцию $\Phi$:
$$\bra{\phi} \ket{\psi} = \int_{-\infty}^\infty \Phi(x)^* \Psi(x) \dd x,$$
такой интеграл назывется _скалярным произведением функций_.

Непрерывную волновую функцию $\Psi$ можно отождествить с кет-вектором
$$\ket{\psi} = \begin{pmatrix} \psi_1 \\ \psi_2 \\ \vdots \end{pmatrix}$$
бесконечномерного гильбертова пространства, комплексно сопряжённую ей --- с бра- $$\bra{\psi} = (\psi_1^* \quad \psi_2^* \quad \cdots),$$
таким образом, волновая функция является вектором состояния.

Состояние квантовой системы описывается общим вектором состояния $\ket{\psi}$, представляющим собой взвешенную по вероятностям $c_i$ сумму ортогональных базисных векторов $\ket{\psi_i}$:
$$\ket{\psi} = \sum_i c_i \ket{\psi_i},$$
это выражение следует трактовать: состояние $\ket{\psi}$ квантовой системы _коллапсирует_ в одно из базисных $\ket{\psi_i}$, причём из ортогональности последних следует, что система не может одновременно находиться в двух или более состояниях: $\bra{\psi_i} \ket{\psi_i} = 0$.

Утверждения, что _а)_ волновая функция описывает частицы, «размазанные в пространстве»; или, что _б)_ квантовая система одновременно находится во множестве разных состояний, не является точными. Более строго, **постулируется**, что длина вектора состояния $\sqrt{ \bra{\psi} \ket{\psi} }$ в гильбертовом пространстве связана с вероятность этого состояния, отсюда вытекает связь волновой функции и амплитуды вероятности [TODO].


правило борна (1926)

## Операторы
Для последовательности дальнейшего изложения дадим несколько определений.

### Гильбертово пространство

::: {.definition #lin-space name="Линейное пространство $L$"}

Множество $L$ называется линейным (или _векторным_) пространством над полем $F$, если для элементов $L$, называемых _векторами_, и элементов $F$, называемых 
_скалярами_, определены две операции:

1. **операция _сложения_ векторов** $+ \colon L \times L \to L$, такая, что $\A \bf x, \bf y, \bf z \in L$ справедливо:

  - $\bf x + \bf y = \bf y + \bf x$ (_коммутативность_),
  - $\bf x + (\bf y + \bf z) = (\bf x + \bf y) + \bf z$ (_ассоциативность_),
  - $\E \bf 0 \in L \colon \bf x + \bf 0 = \bf x$ (существования _нейтрального_ по сложению элемента $\bf 0 \in L$, называемого _нуль-вектором_),
  - $\A \bf x \in L \quad \E (-\bf x) \in L \colon \bf x + (-\bf x) = \bf 0$ (существование _обратного_ по сложению элемента $\bf x + (-\bf x) = \bf 0$);

2. **операция _умножения_ вектора на скаляр** $\; \cdot \; \colon F \times L \to L$, такая, что в дополнение к предыдущему $\A \alpha, \beta \in F$ справедливо:
  - $1 \cdot \bf x = \bf x$ (_унитарность_, или существование _нейтрального_ по умножению элемента $1 \in F$),
  - $\alpha \cdot (\beta \cdot \bf x) = (\alpha \cdot \beta) \cdot x$ (_ассоциативность_),
  - $(\alpha + \beta) \cdot \bf x = \alpha \cdot \bf x + \beta \cdot \bf x$ (_дистрибутивность_ относительно элементов поля $F$),
  - $\alpha \cdot (\bf x + \bf y) = \alpha \cdot \bf x + \alpha \cdot \bf y$ (_дистрибутивность_ относительно элементов пространства $L$).
:::

::: {.definition #scal-prod name="Скалярное произведение $(\dotarg, \dotarg)$"}
Пусть задано линейное пространство $L$ над полем $\R$, тогда _скалярным произведением_ называют функцию $L \times L \to \R$, такую, что $\A \bf x, \bf y \in L, \A \alpha \in \R$ выполняется:

- $(\bf x, \bf x) \ge 0$ и
- $(\bf x, \bf x) = 0 \To \bf x = \bf 0 \in L$ (вкупе: _положительная определённость_),
- $(\alpha \cdot \bf x, \bf y) = \alpha \cdot (\bf x, \bf y)$ и
- $(\bf x + \bf y, \bf z) = (\bf x, \bf z) + (\bf y, \bf z)$ (вкупе: _линейность_),
- $(\bf x, \bf y) = (\bf y, \bf x)$ (_коммутативность_).
:::

::: {.definition #euc-space name="Евклидово пространство $E$"}
Линейное пространство $E$ над полем действительных чисел $\R$, для элементов которого определено скалярное произведение $(\dotarg, \dotarg)$ называют _евклидовым_.
:::

::: {.definition #metric name="Метрика"}
Отображение $\rho \colon M \times M \to \R$ называют _метрикой_ на множестве $M$, если $\A x, y, z \in M$ выполняются _аксиомы расстояния_:

- $\rho(x, y) \ge 0$ (_нетрицательность_),
- $\rho(x, y) = \rho(y, x)$  (_симметрия_),
- $\rho(x, y) \le \rho(x, z) + \rho(z, y)$ (_неравенство треугольника_),
- $\rho(x, y) = 0 \iff x = y$ (_тождественность_).
:::

::: {.definition #met-space name="Метрическое пространство $M$"}
Множество $M$, на котором задана метрика $\rho$, называют **метрическим пространством**.
:::

::: {.definition #fund-seq name="Фундаментальная последовательность"}
Последовательность точек метрического пространства $\{ x_n \}_{n=1}^{\infty}$ называют _фундаментальной_ (или _последовательностью Коши_), если выполняется _условие Коши_:
$$\A \epsilon > 0 \quad \E N_\epsilon \in \N \quad \A n, m \ge N_\epsilon \colon \rho(x_n, x_m) < \epsilon$$
:::

::: {.definition #comp-met name="Полнота"}
Метрическое пространство $M$ называется _полным_, если любая фундаментальная последовательность $\{x_n\}$ его точек имеет предел в этом пространстве:
$$ \E x' \in M \colon \lim_{n \to \infty} \{ x_n \} = x'.$$
:::

::: {.definition #hilb-space name="Гильбертово пространство $\bf H$"}
Полное евклидово пространство, допускающее бесконечную размерность, называют _гильбертовым_.
:::


Состояния квантовых систем описываются векторами в _гильбертовом_ пространстве, на которые действуют _операторами_ --- линейными отображениями.


квантовые наблюдаемые

## Бра и кет векторы


