## Уравнение Шрёдингера

Центральным уравнением для описания молекулярных систем на квантовом уровне является уравнение Шрёдингера, в общем виде оно имеет вид

$$ i \hbar \pdv{}{t} \Psi = \bar H \Psi, $$
где $\Psi = \Psi(\bf r, t)$ --- волновая функция системы, $\hat H = \hat H(p, q, t)$ --- _гамильтониан_, зависящий от обобщённых координат $q$, импульсов $p$ и времени:

В выражение гамильтониана $\hat H$ входят термы кинетической $\hat T$ и потенциальной $\hat U$ энергий, для системы одной частицы с массой $m$ 
$$\hat H := \hat T + \hat U = - \dfrac{\hbar^2}{2m} \nabla^2 + U(\bf r, t).$$

Для системы $N$ частиц выражение гамильтониана^[для простоты в выражении опущен спин электрона] в декартовых координатах
$$\hat H = \underbrace{\sum_{i=1}^N \{ -\dfrac{\hbar^2}{2m_i} (\pdv[2]{}{x_i} + \pdv[2]{}{y_i} + \pdv[2]{}{y_i}) \}}_{\hat T} + \underbrace{\sum_{i<j} U_{i,j}(r_{i,j}) + \sum_{i=1}^N U_i(\bf r_i, t)}_{\hat U},$$
где $\hat T$ зависит от масс $m_i$ и проекций их ускорения, $\hat U$ разбивается на парные^[зависят от расстояния $r_{i,j} = |\bf r_i - \bf r_j|$ между частицами] $U_{i,j}(r_{i,j})$ и непарные^[зависят от положения частицы $r_i$ во внешнем поле] взаимодействия $U_i(\bf r_i)$.

Если внешние поля не зависит от времени $U_i(\bf r_i, t) \equiv U(\bf r_i)$, то гамильтониан является функцией полной энергии $\hat H = \hat H(p, q)$ и тоже не зависит от времени. В этом случае говорят о стационарном^[квантовые наблюдаемые не зависят от времени] состояние молекулярной системы и уравнение Шрёдингера можно привести к иному виду.
Представив волновую функцию $\Psi (\bf r, t) = \phi(\bf r) f(t)$ в виде произведения множителей, зависящих от разных переменных, из [TODO] методом разделения переменных получим сначала
$$ i \hbar \dfrac{1}{f(t)} \pdv{f(t)}{t} = \dfrac{\hat H \phi(\bf r)}{\phi(\bf r)} = E $$
и затем два уравнения
$$i \hbar \pdv{f(t)}{t} = E \cdot f(t), \qquad \hat H \phi(x) = E \phi(\bf r), $$
где $E$ --- наблюдаемая энергия по сути являющаяся собственным значением оператора $\hat H$.
Решением [TODO] будет
$$f(t) = \const \cdot e^{- i E t / \hbar},$$
где $e^{- i E t / \hbar}$ --- _пропагатор_.

Если спектр^[множество собственных значений] гамильтониана дискретен $E = E_1, \cdots, E_n$ и состоянию $E_m$ принадлежит собственная функцию $\phi_n (\bf r)$, то волновая функция
$$\Psi_n (\bf r, t) = \phi_n(\bf r) \cdot e^{-i E_n t / \hbar},$$
и решением уравнения Шрёдингера будет линейная комбинация собственных функций гамильтониана$\Psi_n$ [в силу чего? стр 43]
$$\Psi(\bf r, t) = \sum_n c_n \Psi_n(\bf r, t)$$


## Методы Хартри и Хартри-Фока

## Пост-хартри-фоковские методы

## Базисы