# Интегрирование уравнений движения

Задача МД сводится к решению дифференциального уравнения Ньютона @eq-newton2law для каждой частицы, всего таких уравнений $N$ в векторной форме или $3N$ в скалярной (для трёхмерного пространства), решением системы будут $3N$ проекций координат^[в данном случае декартовых] $r_{i,x}(t)$, $r_{i,y}(t)$, $r_{i,z}(t)$ и $3N$ проекций скоростей $v {i,x}(t)$, $v_{i,y}(t)$, $v_{i,z}(t)$ для всех частиц системы в каждый момент времени.

Известно, что аналитический аппарат классической механики не может справиться с решением подобной задачи уже при $N=3$ (задача трёх тел), поэтому здесь применимы только численные подходы: временна́я переменная $t$ принимается дискретной, прирастающей на *шаг интегрирования* $\delta t$, от решения дифференциальных уравнений переходят к их численному интегрированию, для этого обычно применяется *алгоритм Верле* @Verlet1967 и его модификации; в МД необходимо знать не только положение частиц, но и их скорости; последние можно определить, если использовать этот алгоритм в т.н. *скоростной форме*.

\input{tex/verlet-integration.tex}

Вычисление скорости на половинном шаге позволяет отразить изменение сил, действующих на частицу, в процессе шага интегрирования, таким образом учитывается взаимное влияние атомов.