# Анализ траекторий

## Функция распределения

Результатом интегрирования системы уравнений Ньютона @eq-newton2law будет набор скоростей и координат всех частиц системы, зависящих от времени; их можно объединить в т.н. $6N$-мерное *фазовое пространство* (ФП), каждая точка $({\bf p},{\bf q})$ которого содержит все импульсы
${\bf p}=p_{x,1},p_{y,1},p_{z,1},\cdots,p_{x,N},p_{y,N},p_{z,N}$, и все координаты ${\bf q}=q_{x,1},q_{y,1},q_{z,1},\cdots,q_{x,N},q_{y,N},q_{z,N}$ всех частиц в один момент времени $t$. Любая точка ФП полностью описывает текущее состояние системы, поэтому её можно интерпретировать как микросостояние, а ФП --- как совокупность всех возможных микросостояний.
По мере эволюции системы точки движутся в ФП, проделанные ими пути называют *фазовыми траекториями*. Плотности микросостояний в ФП
приписывают *функцию распределения* $\rho(\mathbf{p},\mathbf{q},t)$, она в состоянии равновесия не должна зависеть от времени, в этом случае точки распределены в ФП с неизменной плотностью; можно сформулировать и более общее утверждение, называемое теоремой Лиувилля:
$$\dv{\rho({\bf p,{\bf q,t)}}}{t}=0,$$ согласно которой плотность фазовых точек при их движении по фазовым траекториям постоянна. Если
$\rho(\mathbf{p},\mathbf{q})$ не зависит от времени явно, то
$$\pdv{\rho({\bf p,{\bf q)}}}{t}=0.$$ Теорема Лиувилля является следствием уравнений Гамильтона:
$$\dot{q}_{i}=\pdv{H({\bf p,{\bf q)}}}{p_{i}}\quad\text{и}\quad\dot{p}_{i}=-\pdv{H({\bf p,{\bf q)}}}{q_{i}},$$
где $H$ --- гамильтониан системы, точкой обозначена полная производная по времени.

Если в результате МД было получено достаточно много наблюдений, можно сказать, что система прошла длинную фазовую траекторию и, вероятно, побывала во всех областях ФП, совокупность этих точек будет задавать геометрический прообраз функции распределения $\rho(\mathbf{p},\mathbf{q})$. Отметим, что закон распределения $\rho(\mathbf{p},\mathbf{q})$ **полностью** описывает ТД систему в статистическом смысле.

## Анализ траекторий

Полученные траектории атомов можно анализировать с позиции конфигурации молекул. Важным параметром конкретной конфигурации (и всех точек траектории в целом) является RMSD^[Root-Mean-Square Deviation] относительно эталонной структуры, по сути это среднеквадратичное отклонение координат атомов от координат соответствующих атомов в эталонной конформации:
$$\mathrm{RMSD}=\sqrt{\dfrac{1}{\Omega}\sum_{i}\omega_{i}\left(\mathbf{r}_{i}-\mathbf{r}_{i}^{\text{ref}}\right)^{2}},$$
где $r_{i}$ и $r_{i}^{\text{ref}}$ --- координаты $i$го атома в текущей и эталонной конфигурации, $\omega_{i}$ --- вес этой пары (обычно принимается за 1), $\Omega$ --- сумма всех весов.
