# Машинные числа

::: callout-note

Заинтересуем читателя простым фрагментом кода на Python.

```{python}
#| code-fold: false
0.1 + 0.2 == 0.3
```

🤔

А теперь на R.

```{r}
#| code-fold: false
0.1 + 0.2 == 0.3
```

😧

Причины этого казуса описаны в этом разделе.

:::
 
### Системы счисления

Для представления чисел мы используем символы: цифры записываются одна за другой, символ точки указывает на нулевой разряд и может опускаться: $23$, $32.0$, $0.32$ --- разные числа. Этот способ записи называется позиционным, информация о разряде кодируется положением цифры. В качестве разрядов людям естественно использовать степени $b = 10$ --- по числу пальцев, $b$ называется *основанием степени счисления*.

Десятичная система --- лишь один способ представления чисел. Число $x \in \R$ можно представить в виде разложения по любому основанию $b$:
$$
x = \sum_{n = -\infty}^{+\infty} a_i \cdot b^n,
$$
где $n$ --- номер разряда (степень основания); $a_i$ --- цифра, их количество равно основанию системы счисления $b$.

Разложение 10чного числа $1917_{10}$ по разрядам $b = 10$ тривиально:
$$
1917_{10} = 1 \cdot b^3 + 9 \cdot b^2 + 1 \cdot b^1 + 7 \cdot b^0.
$$

Чтобы найти запись числа в другой системе счисления ($b = 2$) требуется определить коэффициенты перед степенями $b$:
$$
55_{10} = 1 \cdot b^5 + 1 \cdot b^4 + 0 \cdot b^3 + 1 \cdot b^2 + 1 \cdot b^1 + 1 \cdot b^0 = 110111_2,
$$
аналогично для дробей:
$$
3.5_{10} = 1 \cdot b^1 + 1 \cdot b^0 + 1 \cdot b^{-1} = 11.1_2.
$$

В компьютерах операции производятся в двоичной форме: и процессор, и память работают с битами, поэтому числа представлены либо в двоичной форме, либо ещё более специально.

|   число    | Python  | ассемблер x86 |
| :--------: | :-----: | :-----------: |
| $100_{10}$ |  `100`  |     `100`     |
| $100_{2}$  | `0b100` |    `100b`     |
| $100_{8}$  | `0o100` |    `100o`     |
| $100_{16}$ | `0x100` |    `100x`     |
: Варианты символьной записи чисел в разных системах счисления. Синтаксис зависит от конкретного языка программирования

## Машинное представление числа

В двоичной системе есть только 2 цифры: `0` и `1`, их можно отождествить с «ложно» и «истинно» и работать с двоичными числами средствами машинной логики пораздярно.

### Целые числа

```{python}
import pandas as pd
from math import log10

def sci_form(x):
    
    if abs(x) <= 10**4:
        return x

    sign = 1 if x >= 0 else -1
    x = abs(x)
    exp = int(log10(x))
    mant = x / (10 ** exp)
    return f'{sign * mant:.2f} \cdot 10^{{{exp}}}'

df = pd.DataFrame(
    [
        (n, f'{0} \div {sci_form(2**n)}', f'{sci_form(-2**(n-1))} \div {sci_form(2**(n-1)-1)}')
        for n in [8, 16, 32, 64]
    ],
    columns=['разрадность', 'беззнаковый', 'знаковый']
)

def style(styler):
    return df.style.format('$${0}$$').hide(axis='index')

style(df) 
```

### Числа с плавающей точкой

### Другие форматы

## Машинная арифметика

## Сложение

## Умножение

Умножение на 2 --- сдвиг регистра

## Длинная арифметика

```
import pandas as pd
df = pd.DataFrame([*range(5+1), 10, 100, 128, 256], columns=['10ичное'])
df['2ичное'] = df['10ичное'].apply(lambda n: bin(n)[2:])
df.T
```