# Обозначения {#sec-notation .unnumbered}

## Математическая нотация
::: notae
$a := b$ :- $a$ равно $b$ по определению
$a \equiv b$ :- тождественно равно, т.е. $a$ эквивалентно $b$
$x \sim X$ :- $x$ имеет распределение $X$
$x \propto f(x)$ :- $x$ пропорционально $f(x)$: в широком смысле: *находится в функциональной зависимости*, в узком --- *прямо пропорционально*, т/е *находится в линейной зависимости*
$[x..y)$ :- интервал от $x$ (включая) до $y$ (не включая) $(x, y \in \R)$
$a..b$ :- последовательность $a, a+1, \cdots, b \quad (a, b \in \Z)$
$\nabla = \l( \pdv x, \pdv y, \pdv z \r)$ :- оператор градиента («набла»)
:::

## Константы
::: notae
$h$ :- постоянная Планка
$\hbar := \dfrac h {2\pi}$ :- приведённая постоянная Планка
$k$ :- постоянная Больцмана
$R$ :- универсальная газовая постоянная
:::

## Микропараметры
::: notae
$N$ :- число частиц
$\bf r = (x, y, z)$ :- декартов радиус-вектор
$\bf q = (q_1, q_2, q_3)$ :- обобщённый радиус-вектор
$\bf p = (p_1, p_2, p_3)$ :- обобщённый импульс
$\bf q = \bf q_1, \cdots, \bf q_N$ :- набор обобщённых координат
$\bf p = \bf p_1, \cdots, \bf p_N$ :- набор обобщённых импульсов
$(\bf p, \bf q)$ :- точка фазового пространства
$$\dd \bf q = \dd \bf q_N \cdots \dd \bf q_1 = \\
\dd q_{1,1} \cdots \dd q_{N, 3}$$ :- произведение дифференциалов по всем обобщённым координатам $\bf q$, аналогично для $\bf p$
$E$ :- полная энергия
$T$ :- кинетическая энергия
$U$ :- потенциальная энергия
:::

## Макропараметры
::: notae
### Материальные
$m$ :- масса
$t$ :- время
$T$ :- температура
$P$ :- давление
$V$ :- объём
$\beta := 1/kT$ :- «термодинамическая» $\beta$

### Энергетические
$\cl U$ :- внутренняя энергия
$\cl H$ :- энтальпия
$\cl F$ :- свободная энергия Гельмгольца
$\cl G$ :- свободная энергия Гиббса
$\cl A$ :- свободная энергия (в общем случае)
$\cl H$ :- функция Гамильтона (гамильтониан)

### Статистические
$Q$ :- сумма по состояниям (статсумма)
$Z$ :- конфигурационная часть статсуммы $Q$
:::

## Графические сокращения
::: notae
т/е := то есть
итд := и так далее
итп := и тому подобное
идр := и другие
втч := в том числе
чтд := что и требовалось доказать
тк := так как
ч-л := что-либо; чей-либо
к-л := какой-либо; как-либо
:::

## Аббревиатуры
::: notae
ТД := термодинамика
МД := молекулярная динамика
СП := силовое поле
КМ := квантовая механика
РСА := рентгеноструктурный анализ
ПО := программное обеспечение
КЗ := крупнозернистые (силовые поля)
:::
