on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

env:
  POETRY_VERSION: "1.6.1"
  PYTHON_VERSION: "3.12"

jobs:

  render:
    # setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install 'poetry==${{ env.POETRY_VERSION }}'
      # Quarto dropped support for Pandoc filters, so we need to specify the path to
      # a binary (pandoc-chem-struct). However, GitHub Actions doesn't create a .venv
      # directory in the project directory, and Poetry can't recreate the environment
      # after it's been set up. Therefore, we need to specify this setting before the
      # venv is created.
      - run: poetry config virtualenvs.in-project true
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: poetry
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: make env # reproducible environment
      - run: sudo apt install ffmpeg

      # render
      - run: make render
      
      # upload
      - uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: _site/
  
  publish:
    needs: render
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
        